// ============================================================
// RISK DATA — 42 territories, 6 continents
// ============================================================

const CONTINENTS = {
  'Amérique du Nord': { bonus: 5, color: '#c17f3a', territories: ['Alaska','Alberta','Amérique Centrale','États-Unis de l\'Est','Groenland','Nord-Ouest','Ontario','Québec','États-Unis de l\'Ouest'] },
  'Amérique du Sud': { bonus: 2, color: '#3a8c3a', territories: ['Argentine','Brésil','Pérou','Venezuela'] },
  'Europe':           { bonus: 5, color: '#3a5ac1', territories: ['Grande-Bretagne','Islande','Europe du Nord','Scandinavie','Europe du Sud','Ukraine','Europe de l\'Ouest'] },
  'Afrique':          { bonus: 3, color: '#c1a03a', territories: ['Afrique Centrale','Afrique de l\'Est','Égypte','Madagascar','Afrique du Nord','Afrique du Sud'] },
  'Asie':             { bonus: 7, color: '#8c3a8c', territories: ['Afghanistan','Chine','Inde','Irkoutsk','Japon','Kamchatka','Moyen-Orient','Mongolie','Siam','Sibérie','Oural','Yakoutsk'] },
  'Océanie':          { bonus: 2, color: '#3a8c8c', territories: ['Australie de l\'Est','Indonésie','Nouvelle-Guinée','Australie de l\'Ouest'] }
};

const ADJACENCY = {
  'Alaska': ['Alberta','Nord-Ouest','Kamchatka'],
  'Alberta': ['Alaska','Nord-Ouest','Ontario','États-Unis de l\'Ouest'],
  'Amérique Centrale': ['États-Unis de l\'Ouest','États-Unis de l\'Est','Venezuela'],
  'États-Unis de l\'Est': ['Amérique Centrale','Ontario','Québec','États-Unis de l\'Ouest'],
  'Groenland': ['Nord-Ouest','Ontario','Québec','Islande'],
  'Nord-Ouest': ['Alaska','Alberta','Groenland','Ontario'],
  'Ontario': ['Alberta','États-Unis de l\'Est','Groenland','Nord-Ouest','Québec','États-Unis de l\'Ouest'],
  'Québec': ['États-Unis de l\'Est','Groenland','Ontario'],
  'États-Unis de l\'Ouest': ['Alberta','Amérique Centrale','États-Unis de l\'Est','Ontario'],
  'Argentine': ['Brésil','Pérou'],
  'Brésil': ['Argentine','Pérou','Venezuela','Afrique du Nord'],
  'Pérou': ['Argentine','Brésil','Venezuela'],
  'Venezuela': ['Brésil','Pérou','Amérique Centrale'],
  'Grande-Bretagne': ['Islande','Europe du Nord','Scandinavie','Europe de l\'Ouest'],
  'Islande': ['Grande-Bretagne','Europe du Nord','Scandinavie','Groenland'],
  'Europe du Nord': ['Grande-Bretagne','Islande','Scandinavie','Europe du Sud','Ukraine','Europe de l\'Ouest'],
  'Scandinavie': ['Grande-Bretagne','Islande','Europe du Nord','Ukraine'],
  'Europe du Sud': ['Europe du Nord','Ukraine','Europe de l\'Ouest','Afrique du Nord','Égypte','Moyen-Orient'],
  'Ukraine': ['Europe du Nord','Scandinavie','Europe du Sud','Afghanistan','Moyen-Orient','Oural'],
  'Europe de l\'Ouest': ['Grande-Bretagne','Europe du Nord','Europe du Sud','Afrique du Nord'],
  'Afrique Centrale': ['Afrique de l\'Est','Afrique du Nord','Afrique du Sud'],
  'Afrique de l\'Est': ['Afrique Centrale','Égypte','Madagascar','Afrique du Nord','Afrique du Sud','Moyen-Orient'],
  'Égypte': ['Afrique de l\'Est','Afrique du Nord','Europe du Sud','Moyen-Orient'],
  'Madagascar': ['Afrique de l\'Est','Afrique du Sud'],
  'Afrique du Nord': ['Afrique Centrale','Afrique de l\'Est','Égypte','Europe du Sud','Europe de l\'Ouest','Brésil'],
  'Afrique du Sud': ['Afrique Centrale','Afrique de l\'Est','Madagascar'],
  'Afghanistan': ['Chine','Inde','Moyen-Orient','Oural','Ukraine'],
  'Chine': ['Afghanistan','Inde','Irkoutsk','Mongolie','Siam','Sibérie','Oural'],
  'Inde': ['Afghanistan','Chine','Moyen-Orient','Siam'],
  'Irkoutsk': ['Chine','Kamchatka','Mongolie','Yakoutsk'],
  'Japon': ['Kamchatka','Mongolie'],
  'Kamchatka': ['Irkoutsk','Japon','Mongolie','Yakoutsk','Alaska'],
  'Moyen-Orient': ['Afghanistan','Inde','Europe du Sud','Ukraine','Afrique de l\'Est','Égypte'],
  'Mongolie': ['Chine','Irkoutsk','Japon','Kamchatka','Sibérie'],
  'Siam': ['Chine','Inde','Indonésie'],
  'Sibérie': ['Chine','Irkoutsk','Mongolie','Oural','Yakoutsk'],
  'Oural': ['Afghanistan','Chine','Sibérie','Ukraine'],
  'Yakoutsk': ['Irkoutsk','Kamchatka','Sibérie'],
  'Australie de l\'Est': ['Nouvelle-Guinée','Australie de l\'Ouest'],
  'Indonésie': ['Nouvelle-Guinée','Australie de l\'Ouest','Siam'],
  'Nouvelle-Guinée': ['Australie de l\'Est','Indonésie','Australie de l\'Ouest'],
  'Australie de l\'Ouest': ['Australie de l\'Est','Indonésie','Nouvelle-Guinée']
};

const POSITIONS = {
  'Alaska': [65, 65],
  'Nord-Ouest': [130, 75],
  'Groenland': [260, 45],
  'Alberta': [120, 115],
  'Ontario': [185, 115],
  'Québec': [240, 115],
  'États-Unis de l\'Ouest': [110, 160],
  'États-Unis de l\'Est': [185, 165],
  'Amérique Centrale': [145, 215],
  'Venezuela': [205, 265],
  'Pérou': [200, 315],
  'Brésil': [255, 310],
  'Argentine': [225, 375],
  'Islande': [370, 65],
  'Scandinavie': [445, 60],
  'Grande-Bretagne': [385, 115],
  'Europe du Nord': [450, 115],
  'Europe de l\'Ouest': [400, 165],
  'Europe du Sud': [455, 175],
  'Ukraine': [530, 110],
  'Afrique du Nord': [415, 250],
  'Égypte': [490, 240],
  'Afrique de l\'Est': [520, 305],
  'Afrique Centrale': [460, 320],
  'Afrique du Sud': [480, 390],
  'Madagascar': [555, 360],
  'Oural': [590, 85],
  'Sibérie': [660, 70],
  'Yakoutsk': [730, 60],
  'Kamchatka': [810, 65],
  'Irkoutsk': [720, 120],
  'Mongolie': [720, 170],
  'Chine': [680, 175],
  'Afghanistan': [600, 165],
  'Moyen-Orient': [560, 225],
  'Inde': [640, 240],
  'Siam': [710, 255],
  'Japon': [800, 165],
  'Indonésie': [750, 330],
  'Nouvelle-Guinée': [820, 320],
  'Australie de l\'Ouest': [780, 395],
  'Australie de l\'Est': [845, 385]
};

// Grid positions for each die face (3x3 grid, 1-indexed left-to-right top-to-bottom)
const DIE_PIPS = {
  1: [5],
  2: [3, 7],
  3: [3, 5, 7],
  4: [1, 3, 7, 9],
  5: [1, 3, 5, 7, 9],
  6: [1, 3, 4, 6, 7, 9]
};
